version: '3.5'

services:
  cups:
    container_name: cups
    image: chuckcharlie/cups-avahi-airprint
    #build: .
    restart: always
    network_mode: "host"
    environment:
      CUPSADMIN: cups
      CUPSPASSWORD: cups
      # TZ: Europe/Vienna  # optional, defaults to UTC
    volumes:
      - "./config:/config"